on:
  push:
  workflow_dispatch:

name: CI Checks

jobs:
  code_checks:
    name: Build and Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install NPM Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Unit Tests
        env:
          TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
        run: yarn vitest
